### ISSUE TITLE
Accompanying paper?

### ISSUE THREAD

**Issue by bbruhh** [jcvasquezc/phonet#1]
Hi

Have you published a paper describing this tool?

Also, as I understand, the toolkit will compute probabilities for each phoneme for a given audio file. **Does it work for free speech too or just specific utterances**.

Thanks

**Comment by jcvasquezc** [comment]
Hi

Currently there is a paper under evaluation, which you can download from here: 
https://docs.wixstatic.com/ugd/38e933_55c916b65efa4e3298848bd96cf91773.pdf

About the other question, yes, the model was trained with the aim to evaluate spotaneous speech utterances.

You can find all the information in the paper

**Comment by bbruhh** [comment]
Thanks, the paper looks Interspeech format. I guess it is submitted to Interspeech 2019
