### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by Barbany** [jcvasquezc/phonet#2]
I find your padding strategy in `get_feat` function of file `phonet.py` quite weird. First of all, you compute

```
fill=len(signal)%int(fs*self.size_frame*self.len_seq)
```

so with the default parameters this means that if a signal has length say strictly less than `16000=int(fs*self.size_frame*self.len_seq)`, then you are simply doubling its size regardless of the length (normally you pad to fill frames instead).

Moreover, in the next line you do:

```
fillv=0.05*np.random.randn(fill)-self.size_frame
```

so you substract the value size frame to the random signal used for padding. I don't know why you'd do that.

**Comment by jcvasquezc** [comment]
Hi

The padding is made to guarantee the signal has a length multiple of 1 second, which id the length of the frames for the BGRUs

However, you are right, and this does not work for signals shorter than a second

On the other hand, the substraction of the term `self.size_frame` does not have to be there, as well

I will fix this as soon as possible

**Comment by Barbany** [comment]
If you want to have a length multiple of 1 second then you should have something like
``` fill = len(signal) - len(signal)%int(fs*self.size_frame*self.len_seq)```
so if you have say a signal of 1 min 59 s, you are adding 1 s. Your current code would add 59 s resulting in 2 min 58 s, so also not multiple of 1 s. Hence the problem is not just for signals shorter than a second.

**Comment by jcvasquezc** [comment]
Hi

Now I know what yo mean

I will fix it ASAP

**Comment by jcvasquezc** [comment]
Take a look into the new version

Now its done

Tell me if you agree with the updated version

`        fill=fs-len(signal)%int(fs*self.size_frame*self.len_seq)+int(fs*self.size_frame)
        fillv=0.05*np.random.randn(fill)
        signal=np.hstack((signal,fillv))`

**Comment by Barbany** [comment]
If you want to fill an integer number of seconds and add to this extra padding samples corresponding to one frame regardless of your signal length, then your code is ok.

If this is the case, I don't know why you want to add an extra frame, since you told me the purpose of the filling was to have a length multiple of 1s. Instead even when the signal is exactly of 1s, you add an extra 0.025s of noise with your current parameters.

Another question is why you want to have a length multiple of 1s if according to your paper you train on chunks of 0.5s.

A side note is that even if your code works for the current parameters, using
``` fill=int(fs*self.size_frame*self.len_seq)-len(signal)%int(fs*self.size_frame*self.len_seq)+int(fs*self.size_frame)```
would work for different size frame and sequence length parameters (otherwise same problem of "non-increasing" padding length w.r.t. original length).

**Comment by jcvasquezc** [comment]
Yes, you are right

The additional 0.025 sec is because a rounding aspect that appears in `get_phon_wav`

For the paper, the length of the frame was 500 ms, yes

The current version located here was optimized after the paper, and it works with 1 second length, and the parallel bank of BGRUs was replaced by a single network trained with a multi-task learning scheme.

**Comment by Barbany** [comment]
Sorry for insisting again and not spotting the issue before. When the length is indeed a multiple of 1 s, the modulo operator gives zero, so the filling is the one corresponding to one frame and one extra second. One way to solve it is as follows (probably there are better ways).
```
mult = int(fs*self.size_frame*self.len_seq)
fill = (mult - len(signal) % mult) % mult + int(fs * self.size_frame)
```

**Comment by jcvasquezc** [comment]
Hi

You are right

Thanks for letting me know

Its already fixed


best
